#!/usr/bin/env python3
"""
HTJR/HTS UFO controller based on the decompiled HTJR-UFO APK.

This opens the drone's RTSP stream over UDP, then sends the raw 13-byte
HTJR flight packet to the RTCP UDP port from that RTSP session.
"""

from __future__ import annotations

import argparse
import os
import queue
import random
import re
import select
import shutil
import socket
import subprocess
import sys
import termios
import threading
import time
import tty
from dataclasses import dataclass
from typing import Callable


DEFAULT_DRONE_IP = "192.168.1.1"
DEFAULT_RTSP_PORT = 7070
DEFAULT_RTSP_URL = "rtsp://192.168.1.1:7070/webcam"
APK_SPEED_BYTES = (30, 60, 100)


def clamp_byte(value: int) -> int:
    return max(0, min(255, int(value)))


def normalize_speed_byte(value: int) -> int:
    """Keep the packet on the same speed bytes the APK actually sends."""
    if value in APK_SPEED_BYTES:
        return value
    closest = min(APK_SPEED_BYTES, key=lambda speed: abs(speed - value))
    print(f"[WARN] speed {value} is not an APK speed byte; using {closest}")
    return closest


@dataclass
class HtjrPacketState:
    ail: int = 128
    ele: int = 128
    thr: int = 128
    rudd: int = 128
    speed: int = 30
    altitude_hold: bool = False
    flyup: bool = False
    flydown: bool = False
    return_mode: bool = False
    fixed_direction_rotate: bool = False
    headless: bool = False
    rotate: bool = False
    emergency_down: bool = False
    gyro_calibrate: bool = False
    trim_ele: int = 128
    trim_ail: int = 128
    trim_rudd: int = 128
    light: bool = False
    roll_flip: bool = False


def scaled_axis_byte(value: int, speed: int, roll_flip: bool) -> int:
    """Apply the APK's AIL/ELE speed limiting before putting bytes on the wire."""
    value = clamp_byte(value)
    if roll_flip:
        return value
    factor = normalize_speed_byte(speed) / 100.0
    if value < 128:
        return 128 - int((128 - value) * factor)
    if value > 128:
        return 128 + int((value - 128) * factor)
    return value


def build_htjr_packet(state: HtjrPacketState) -> bytes:
    """Build the 13-byte packet generated by FlyController.java."""
    speed = normalize_speed_byte(state.speed)
    ail = scaled_axis_byte(state.ail, speed, state.roll_flip)
    ele = scaled_axis_byte(state.ele, speed, state.roll_flip)
    thr = clamp_byte(state.thr)
    rudd = clamp_byte(state.rudd)
    speed_flags = (speed << 1) | int(state.altitude_hold)
    checksum = ail ^ ele ^ thr ^ rudd ^ speed_flags

    mode_flags = (
        int(state.flyup)
        | (int(state.flydown) << 1)
        | (int(state.return_mode) << 2)
        | (int(state.fixed_direction_rotate) << 3)
        | (int(state.headless) << 4)
        | (int(state.rotate) << 5)
        | (int(state.emergency_down) << 6)
        | (int(state.gyro_calibrate) << 7)
    )
    extra_flags = (int(state.light) << 1) | int(state.roll_flip)

    return bytes(
        [
            0x66,
            ail,
            ele,
            thr,
            rudd,
            speed_flags,
            checksum,
            0x99,
            clamp_byte(state.trim_ele),
            clamp_byte(state.trim_ail),
            clamp_byte(state.trim_rudd),
            mode_flags,
            extra_flags,
        ]
    )


class RtspUdpSession:
    def __init__(
        self,
        host: str,
        port: int,
        url: str,
        client_port_base: int | None = None,
        verbose: bool = False,
    ) -> None:
        self.host = host
        self.port = port
        self.url = url
        self.verbose = verbose
        self.cseq = 1
        self.session: str | None = None
        self.server_rtp_port: int | None = None
        self.server_rtcp_port: int | None = None
        self.last_rtp_addr: tuple[str, int] | None = None
        self.last_rtcp_addr: tuple[str, int] | None = None
        self.describe_response = ""
        self.sdp = ""
        self.video_payload_type: int | None = None
        self.video_codec: str | None = None
        self.rtp_callbacks: list[Callable[[bytes], None]] = []
        self.running = False

        self.tcp = socket.create_connection((self.host, self.port), timeout=5)
        self.rtp, self.rtcp, self.client_rtp_port, self.client_rtcp_port = (
            self._bind_udp_pair(client_port_base)
        )
        for sock in (self.rtp, self.rtcp):
            try:
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 4 * 1024 * 1024)
            except OSError:
                pass
        self.rtp.settimeout(0.2)
        self.rtcp.settimeout(0.2)

    def _bind_udp_pair(
        self, requested_base: int | None
    ) -> tuple[socket.socket, socket.socket, int, int]:
        bases: list[int] = []
        if requested_base is not None:
            bases.append(requested_base if requested_base % 2 == 0 else requested_base - 1)
        bases.extend(random.randrange(10000, 40000, 2) for _ in range(100))

        last_error: OSError | None = None
        for base in bases:
            rtp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            rtcp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            try:
                rtp.bind(("", base))
                rtcp.bind(("", base + 1))
                return rtp, rtcp, base, base + 1
            except OSError as exc:
                last_error = exc
                rtp.close()
                rtcp.close()

        raise RuntimeError(f"Could not bind local RTP/RTCP ports: {last_error}")

    def request(self, method: str, url: str, extra_headers: str = "") -> str:
        msg = (
            f"{method} {url} RTSP/1.0\r\n"
            f"CSeq: {self.cseq}\r\n"
            "User-Agent: HTJR-Fixed-Python\r\n"
            f"{extra_headers}"
            "\r\n"
        )
        self.cseq += 1

        if self.verbose:
            print(f"\n[RTSP] >>> {method} {url}")
            print(msg.rstrip())

        self.tcp.sendall(msg.encode("ascii"))
        response = self._read_response()

        if self.verbose:
            print("[RTSP] <<<")
            print(response.split("\r\n\r\n", 1)[0])

        return response

    def _read_response(self) -> str:
        data = b""
        while b"\r\n\r\n" not in data:
            chunk = self.tcp.recv(4096)
            if not chunk:
                raise RuntimeError("RTSP connection closed while reading headers")
            data += chunk

        header, body = data.split(b"\r\n\r\n", 1)
        header_text = header.decode("latin1", errors="replace")
        content_length = 0
        for line in header_text.splitlines():
            if line.lower().startswith("content-length:"):
                content_length = int(line.split(":", 1)[1].strip())
                break

        while len(body) < content_length:
            body += self.tcp.recv(content_length - len(body))

        return header_text + "\r\n\r\n" + body.decode("latin1", errors="replace")

    @staticmethod
    def _status_code(response: str) -> int | None:
        first = response.splitlines()[0] if response else ""
        match = re.search(r"RTSP/\S+\s+(\d+)", first)
        return int(match.group(1)) if match else None

    @staticmethod
    def _header(response: str, name: str) -> str | None:
        needle = name.lower() + ":"
        for line in response.splitlines():
            if line.lower().startswith(needle):
                return line.split(":", 1)[1].strip()
        return None

    def _control_url_from_describe(self, describe: str) -> str:
        content_base = self._header(describe, "Content-Base")
        base = content_base or self.url
        for line in describe.splitlines():
            line = line.strip()
            if not line.startswith("a=control:"):
                continue

            value = line.split(":", 1)[1].strip()
            if value == "*":
                return self.url
            if value.startswith("rtsp://"):
                return value
            return base.rstrip("/") + "/" + value.lstrip("/")

        return self.url.rstrip("/") + "/track0"

    def connect(self) -> None:
        options = self.request("OPTIONS", self.url)
        self._require_ok(options, "OPTIONS")

        describe = self.request("DESCRIBE", self.url, "Accept: application/sdp\r\n")
        self._require_ok(describe, "DESCRIBE")
        self.describe_response = describe
        self.sdp = describe.split("\r\n\r\n", 1)[1] if "\r\n\r\n" in describe else ""
        self._parse_sdp_media()

        control_url = self._control_url_from_describe(describe)
        print("[RTSP] control URL:", control_url)
        if self.video_codec:
            print("[RTSP] video:", self.video_payload_type, self.video_codec)

        setup = self._setup_udp(control_url)
        self.session = self._parse_session(setup)
        self._parse_transport(setup)

        print("[RTSP] session:", self.session)
        print("[RTSP] client RTP/RTCP:", self.client_rtp_port, self.client_rtcp_port)
        print("[RTSP] server RTP/RTCP:", self.server_rtp_port, self.server_rtcp_port)

        play = self.request(
            "PLAY",
            self.url,
            f"Session: {self.session}\r\nRange: npt=0.000-\r\n",
        )
        self._require_ok(play, "PLAY")

        self.running = True
        threading.Thread(target=self._drain_rtp, daemon=True).start()
        threading.Thread(target=self._drain_rtcp, daemon=True).start()
        self._ensure_remote_rtcp_port()

    def _setup_udp(self, control_url: str) -> str:
        transports = [
            "RTP/AVP;unicast",
            "RTP/AVP/UDP;unicast",
        ]
        last_response = ""
        for transport in transports:
            setup = self.request(
                "SETUP",
                control_url,
                (
                    f"Transport: {transport};"
                    f"client_port={self.client_rtp_port}-{self.client_rtcp_port}\r\n"
                ),
            )
            last_response = setup
            if self._status_code(setup) == 200:
                return setup

        raise RuntimeError(
            "SETUP failed. Last response:\n"
            + last_response.split("\r\n\r\n", 1)[0]
        )

    def _require_ok(self, response: str, method: str) -> None:
        code = self._status_code(response)
        if code != 200:
            raise RuntimeError(
                f"{method} failed with RTSP status {code}:\n"
                + response.split("\r\n\r\n", 1)[0]
            )

    def _parse_session(self, response: str) -> str:
        value = self._header(response, "Session")
        if not value:
            raise RuntimeError("SETUP succeeded but did not return a Session header")
        return value.split(";", 1)[0].strip()

    def _parse_transport(self, response: str) -> None:
        transport = self._header(response, "Transport") or ""
        print("[RTSP] transport:", transport)
        match = re.search(r"server_port=(\d+)-(\d+)", transport, re.I)
        if match:
            self.server_rtp_port = int(match.group(1))
            self.server_rtcp_port = int(match.group(2))

    def _parse_sdp_media(self) -> None:
        video_payloads: list[int] = []
        in_video = False
        for line in self.sdp.splitlines():
            line = line.strip()
            if line.startswith("m="):
                parts = line.split()
                in_video = bool(parts and parts[0].lower() == "m=video")
                if in_video:
                    video_payloads = [int(part) for part in parts[3:] if part.isdigit()]
                    if video_payloads:
                        self.video_payload_type = video_payloads[0]
                continue

            if not in_video:
                continue

            match = re.match(r"a=rtpmap:(\d+)\s+([^/\s;]+)", line, re.I)
            if match:
                payload_type = int(match.group(1))
                if video_payloads and payload_type not in video_payloads:
                    continue
                self.video_payload_type = payload_type
                self.video_codec = match.group(2).upper()
                return

        # Static RTP payload type 26 is JPEG, and older cameras often omit rtpmap.
        if self.video_codec is None and self.video_payload_type == 26:
            self.video_codec = "JPEG"

    def add_rtp_callback(self, callback: Callable[[bytes], None]) -> None:
        self.rtp_callbacks.append(callback)

    def _ensure_remote_rtcp_port(self) -> None:
        if self.server_rtcp_port is not None:
            return

        print("[RTSP] no server RTCP port in SETUP; waiting briefly to infer it")
        deadline = time.time() + 2.0
        while time.time() < deadline:
            if self.last_rtcp_addr:
                self.server_rtcp_port = self.last_rtcp_addr[1]
                return
            if self.last_rtp_addr:
                self.server_rtp_port = self.last_rtp_addr[1]
                self.server_rtcp_port = self.last_rtp_addr[1] + 1
                return
            time.sleep(0.05)

        raise RuntimeError("Could not determine the drone's RTCP port")

    def _drain_rtp(self) -> None:
        while self.running:
            try:
                data, addr = self.rtp.recvfrom(65535)
                self.last_rtp_addr = addr
                for callback in tuple(self.rtp_callbacks):
                    callback(data)
            except socket.timeout:
                continue
            except OSError:
                break

    def _drain_rtcp(self) -> None:
        while self.running:
            try:
                _, addr = self.rtcp.recvfrom(65535)
                self.last_rtcp_addr = addr
            except socket.timeout:
                continue
            except OSError:
                break

    def send_control(self, packet: bytes) -> None:
        if self.server_rtcp_port is None:
            raise RuntimeError("No server RTCP port known yet")
        self.rtcp.sendto(packet, (self.host, self.server_rtcp_port))

    def close(self) -> None:
        self.running = False
        try:
            if self.session:
                self.request("TEARDOWN", self.url, f"Session: {self.session}\r\n")
        except Exception:
            pass
        for sock in (self.tcp, self.rtp, self.rtcp):
            try:
                sock.close()
            except Exception:
                pass


@dataclass
class RtpPacket:
    marker: bool
    payload_type: int
    sequence: int
    timestamp: int
    payload: bytes


def parse_rtp_packet(data: bytes) -> RtpPacket | None:
    if len(data) < 12:
        return None
    version = data[0] >> 6
    if version != 2:
        return None

    csrc_count = data[0] & 0x0F
    has_extension = bool(data[0] & 0x10)
    has_padding = bool(data[0] & 0x20)
    header_len = 12 + (csrc_count * 4)
    if len(data) < header_len:
        return None

    if has_extension:
        if len(data) < header_len + 4:
            return None
        ext_words = int.from_bytes(data[header_len + 2 : header_len + 4], "big")
        header_len += 4 + (ext_words * 4)
        if len(data) < header_len:
            return None

    payload_end = len(data)
    if has_padding:
        pad_len = data[-1]
        if pad_len == 0 or pad_len > payload_end - header_len:
            return None
        payload_end -= pad_len

    return RtpPacket(
        marker=bool(data[1] & 0x80),
        payload_type=data[1] & 0x7F,
        sequence=int.from_bytes(data[2:4], "big"),
        timestamp=int.from_bytes(data[4:8], "big"),
        payload=data[header_len:payload_end],
    )


JPEG_ZIGZAG = (
    0,
    1,
    8,
    16,
    9,
    2,
    3,
    10,
    17,
    24,
    32,
    25,
    18,
    11,
    4,
    5,
    12,
    19,
    26,
    33,
    40,
    48,
    41,
    34,
    27,
    20,
    13,
    6,
    7,
    14,
    21,
    28,
    35,
    42,
    49,
    56,
    57,
    50,
    43,
    36,
    29,
    22,
    15,
    23,
    30,
    37,
    44,
    51,
    58,
    59,
    52,
    45,
    38,
    31,
    39,
    46,
    53,
    60,
    61,
    54,
    47,
    55,
    62,
    63,
)

JPEG_LUMA_QUANT = (
    16,
    11,
    10,
    16,
    24,
    40,
    51,
    61,
    12,
    12,
    14,
    19,
    26,
    58,
    60,
    55,
    14,
    13,
    16,
    24,
    40,
    57,
    69,
    56,
    14,
    17,
    22,
    29,
    51,
    87,
    80,
    62,
    18,
    22,
    37,
    56,
    68,
    109,
    103,
    77,
    24,
    35,
    55,
    64,
    81,
    104,
    113,
    92,
    49,
    64,
    78,
    87,
    103,
    121,
    120,
    101,
    72,
    92,
    95,
    98,
    112,
    100,
    103,
    99,
)

JPEG_CHROMA_QUANT = (
    17,
    18,
    24,
    47,
    99,
    99,
    99,
    99,
    18,
    21,
    26,
    66,
    99,
    99,
    99,
    99,
    24,
    26,
    56,
    99,
    99,
    99,
    99,
    99,
    47,
    66,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
    99,
)

JPEG_DHT = bytes.fromhex(
    "ffc401a2"
    "0000010501010101010100000000000000000102030405060708090a0b"
    "100002010303020403050504040000017d010203000411051221314106"
    "13516107227114328191a1082342b1c11552d1f02433627282090a16"
    "1718191a25262728292a3435363738393a434445464748494a535455"
    "565758595a636465666768696a737475767778797a83848586878889"
    "8a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9"
    "bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae1e2e3e4e5e6e7"
    "e8e9eaf1f2f3f4f5f6f7f8f9fa"
    "0100030101010101010101010000000000000102030405060708090a0b"
    "11000201020404030407050404000102770001020311040521310612"
    "41510761711322328108144291a1b1c109233352f0156272d10a16"
    "2434e125f11718191a262728292a35363738393a43444546474849"
    "4a535455565758595a636465666768696a737475767778797a828384"
    "85868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4"
    "b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae2e3"
    "e4e5e6e7e8e9eaf2f3f4f5f6f7f8f9fa"
)


class RtpVideoViewer:
    def __init__(
        self,
        session: RtspUdpSession,
        title: str = "HTJR Fixed Camera",
        debug: bool = False,
        debug_limit: int = 120,
        dump_dir: str | None = None,
        dump_limit: int = 8,
        capture_dir: str = "captures",
    ) -> None:
        self.session = session
        self.title = title
        self.debug = debug
        self.debug_limit = debug_limit
        self.debug_print_count = 0
        self.dump_dir = dump_dir
        self.dump_limit = dump_limit
        self.dump_count = 0
        self.capture_dir = capture_dir
        self.capture_count = 0
        self.latest_frame = None
        self.latest_frame_lock = threading.Lock()
        if self.dump_dir:
            os.makedirs(self.dump_dir, exist_ok=True)
        os.makedirs(self.capture_dir, exist_ok=True)
        self.packets: queue.Queue[bytes] = queue.Queue(maxsize=3000)
        self.running = False
        self.closed = False
        self.thread: threading.Thread | None = None
        self.h264_process: subprocess.Popen[bytes] | None = None
        self.h264_warned = False
        self.h264_in_fu = False
        self.h264_last_sequence: int | None = None
        self.jpeg_timestamp: int | None = None
        self.jpeg_chunks: dict[int, bytes] = {}
        self.jpeg_direct_parts: list[bytes] = []
        self.jpeg_expected_offset = 0
        self.jpeg_valid = True
        self.jpeg_last_sequence: int | None = None
        self.jpeg_info: dict[str, int | bytes | None] | None = None
        self.rtp_packet_count = 0
        self.decoded_frame_count = 0
        self.jpeg_drop_count = 0
        self.jpeg_frame_count = 0
        self.jpeg_drop_reasons: dict[str, int] = {}
        self.jpeg_last_drop_reason = ""
        self.last_payload_type: int | None = None
        self.last_sequence: int | None = None
        self.last_packet_time = 0.0
        self.last_status_print = 0.0
        self.last_console_status = 0.0

    def on_rtp_packet(self, data: bytes) -> None:
        if self.closed:
            return
        try:
            self.packets.put_nowait(data)
        except queue.Full:
            try:
                self.packets.get_nowait()
            except queue.Empty:
                pass
            try:
                self.packets.put_nowait(data)
            except queue.Full:
                pass

    def start(self) -> None:
        if self.running:
            return
        self.running = True
        codec = self._codec()
        if codec in {"H264", "H.264", "AVC"}:
            self._ensure_h264_player()
        print(f"[VIDEO] viewer started for RTP codec: {codec or 'auto'}")
        self.thread = threading.Thread(target=self._loop, daemon=True)
        self.thread.start()

    def stop(self) -> None:
        self.closed = True
        self.running = False
        if self.h264_process is not None:
            try:
                self.h264_process.terminate()
            except Exception:
                pass

    def _codec(self) -> str:
        return (self.session.video_codec or "").upper()

    def _loop(self) -> None:
        cv2 = None
        np = None
        try:
            try:
                import cv2 as cv2_module
                import numpy as np_module

                cv2 = cv2_module
                np = np_module
                cv2.namedWindow(self.title, cv2.WINDOW_NORMAL)
                cv2.resizeWindow(self.title, 640, 480)
                self._show_status(cv2, np, "Waiting for RTP video packets...")
            except ImportError as exc:
                print("[VIDEO] OpenCV/numpy missing; cannot show RTP video:", exc)
                return
            except Exception as exc:
                print("[VIDEO] could not open OpenCV window:", exc)

            while self.running:
                try:
                    data = self.packets.get(timeout=0.05)
                except queue.Empty:
                    self._show_wait_status(cv2, np)
                    continue

                packet = parse_rtp_packet(data)
                if packet is None:
                    continue
                self.rtp_packet_count += 1
                self.last_payload_type = packet.payload_type
                self.last_sequence = packet.sequence
                self.last_packet_time = time.time()
                if (
                    self.session.video_payload_type is not None
                    and packet.payload_type != self.session.video_payload_type
                ):
                    continue

                codec = self._codec()
                if codec in {"H264", "H.264", "AVC"} or self._looks_like_h264(packet):
                    self._write_h264(packet)
                    self._show_h264_status(cv2, np)
                    continue

                jpeg_bytes = self._jpeg_from_packet(packet)
                if jpeg_bytes is None:
                    self._show_wait_status(cv2, np)
                    continue

                self._dump_jpeg(jpeg_bytes)
                frame = self._decode_jpeg(cv2, np, jpeg_bytes)
                if frame is None:
                    self._drop_jpeg("opencv_decode_failed")
                    self._show_wait_status(cv2, np)
                    continue
                if self._looks_like_decoder_fill(frame, np):
                    self._drop_jpeg("decoder_gray_fill")
                    self._show_wait_status(cv2, np)
                    continue
                self.decoded_frame_count += 1
                with self.latest_frame_lock:
                    self.latest_frame = frame.copy()
                cv2.imshow(self.title, frame)
                key = cv2.waitKey(1) & 0xFF
                if key == ord("q"):
                    self.running = False
                    break
                if key == ord(" "):
                    self.capture_picture()
        finally:
            if cv2 is not None:
                try:
                    cv2.destroyWindow(self.title)
                except Exception:
                    pass

    def _show_wait_status(self, cv2, np) -> None:
        if cv2 is None or np is None:
            return
        now = time.time()
        if now - self.last_status_print < 0.25:
            return

        if self.rtp_packet_count == 0:
            status = "Waiting for RTP video packets..."
            detail = "RTSP PLAY succeeded, but no RTP has arrived yet."
        else:
            codec = self._codec() or "auto"
            status = "RTP packets are arriving; no decoded frame yet."
            detail = (
                f"codec={codec} payload={self.last_payload_type} "
                f"seq={self.last_sequence} packets={self.rtp_packet_count} "
                f"decoded={self.decoded_frame_count} dropped={self.jpeg_drop_count}"
            )
            if self.jpeg_last_drop_reason:
                detail += f" last_drop={self.jpeg_last_drop_reason}"
            console_detail = detail
            drop_summary = self._drop_summary()
            if drop_summary:
                console_detail += f" reasons={drop_summary}"
            if now - self.last_console_status >= 2.0:
                print("[VIDEO]", console_detail)
                self.last_console_status = now

        self.last_status_print = now
        if self.decoded_frame_count > 0:
            key = cv2.waitKey(1) & 0xFF
            if key == ord("q"):
                self.running = False
            elif key == ord(" "):
                self.capture_picture()
            return
        self._show_status(cv2, np, status, detail)

    def _show_h264_status(self, cv2, np) -> None:
        if cv2 is None or np is None:
            return
        player = "ffplay active" if self.h264_process is not None else "ffplay unavailable"
        detail = (
            f"H264 RTP packets: {self.rtp_packet_count}, payload={self.last_payload_type}, "
            f"seq={self.last_sequence}, {player}"
        )
        self._show_status(cv2, np, "H264 stream detected.", detail)

    def _show_status(self, cv2, np, line1: str, line2: str = "") -> None:
        if cv2 is None or np is None:
            return
        image = np.zeros((480, 640, 3), dtype=np.uint8)
        image[:] = (26, 28, 30)
        lines = [
            "HTJR Fixed Camera",
            line1,
        ]
        if line2:
            lines.append(line2)
        lines.append("Press q in this window to close video.")

        y = 90
        for idx, line in enumerate(lines):
            scale = 0.8 if idx == 0 else 0.55
            color = (235, 235, 235) if idx == 0 else (180, 220, 180)
            cv2.putText(
                image,
                line[:82],
                (34, y),
                cv2.FONT_HERSHEY_SIMPLEX,
                scale,
                color,
                1,
                cv2.LINE_AA,
            )
            y += 46
        cv2.imshow(self.title, image)
        key = cv2.waitKey(1) & 0xFF
        if key == ord("q"):
            self.running = False
        elif key == ord(" "):
            self.capture_picture()

    def capture_picture(self) -> None:
        with self.latest_frame_lock:
            frame = None if self.latest_frame is None else self.latest_frame.copy()
        if frame is None:
            print("[PHOTO] no decoded camera frame yet")
            return

        try:
            import cv2
        except ImportError as exc:
            print("[PHOTO] OpenCV missing; cannot save picture:", exc)
            return

        self.capture_count += 1
        stamp = time.strftime("%Y%m%d-%H%M%S")
        path = os.path.join(self.capture_dir, f"htjr_{stamp}_{self.capture_count:04d}.jpg")
        if cv2.imwrite(path, frame):
            print("[PHOTO] saved:", path)
        else:
            print("[PHOTO] failed to save:", path)

    def _decode_jpeg(self, cv2, np, jpeg_bytes: bytes):
        source = np.frombuffer(jpeg_bytes, dtype=np.uint8)

        # OpenCV/libjpeg prints corrupt-frame warnings directly to fd 2. The
        # structured drop logs below are more useful, so keep stderr quiet here.
        saved_stderr = None
        devnull = None
        try:
            try:
                sys.stderr.flush()
                saved_stderr = os.dup(2)
                devnull = os.open(os.devnull, os.O_WRONLY)
                os.dup2(devnull, 2)
            except OSError:
                saved_stderr = None
                devnull = None
            return cv2.imdecode(source, cv2.IMREAD_COLOR)
        finally:
            if saved_stderr is not None:
                try:
                    os.dup2(saved_stderr, 2)
                finally:
                    os.close(saved_stderr)
            if devnull is not None:
                os.close(devnull)

    def _dump_jpeg(self, jpeg_bytes: bytes) -> None:
        if not self.dump_dir or self.dump_count >= self.dump_limit:
            return
        self.dump_count += 1
        path = os.path.join(
            self.dump_dir,
            f"frame_{self.dump_count:04d}_{len(jpeg_bytes)}b.jpg",
        )
        try:
            with open(path, "wb") as file:
                file.write(jpeg_bytes)
            self._debug(f"dumped jpeg path={path} bytes={len(jpeg_bytes)}", force=True)
        except OSError as exc:
            self._debug(f"could not dump jpeg path={path} error={exc}", force=True)

    def _ensure_h264_player(self) -> None:
        if self.h264_process is not None or self.h264_warned:
            return
        ffplay = shutil.which("ffplay")
        if not ffplay:
            print("[VIDEO] H264 RTP detected but ffplay is not installed; video will not open")
            self.h264_warned = True
            return
        try:
            self.h264_process = subprocess.Popen(
                [
                    ffplay,
                    "-loglevel",
                    "warning",
                    "-fflags",
                    "nobuffer",
                    "-flags",
                    "low_delay",
                    "-framedrop",
                    "-sync",
                    "ext",
                    "-f",
                    "h264",
                    "-i",
                    "-",
                ],
                stdin=subprocess.PIPE,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            print("[VIDEO] opened ffplay for H264 RTP")
        except Exception as exc:
            print("[VIDEO] could not start ffplay:", exc)
            self.h264_warned = True

    def _write_h264(self, packet: RtpPacket) -> None:
        self._ensure_h264_player()
        if self.h264_process is None or self.h264_process.stdin is None:
            return

        for chunk in self._h264_chunks(packet):
            try:
                self.h264_process.stdin.write(chunk)
                self.h264_process.stdin.flush()
            except (BrokenPipeError, OSError):
                self.h264_process = None
                self.h264_warned = True
                return

    def _h264_chunks(self, packet: RtpPacket) -> list[bytes]:
        payload = packet.payload
        if not payload:
            return []

        if self.h264_last_sequence is not None and (
            (self.h264_last_sequence + 1) & 0xFFFF
        ) != packet.sequence:
            self.h264_in_fu = False
        self.h264_last_sequence = packet.sequence

        nal_type = payload[0] & 0x1F
        start_code = b"\x00\x00\x00\x01"

        if 1 <= nal_type <= 23:
            self.h264_in_fu = False
            return [start_code + payload]

        if nal_type == 24:
            chunks: list[bytes] = []
            pos = 1
            while pos + 2 <= len(payload):
                size = int.from_bytes(payload[pos : pos + 2], "big")
                pos += 2
                if size <= 0 or pos + size > len(payload):
                    break
                chunks.append(start_code + payload[pos : pos + size])
                pos += size
            return chunks

        if nal_type == 28 and len(payload) >= 2:
            fu_indicator = payload[0]
            fu_header = payload[1]
            is_start = bool(fu_header & 0x80)
            is_end = bool(fu_header & 0x40)
            nal_header = bytes([(fu_indicator & 0xE0) | (fu_header & 0x1F)])
            if is_start:
                self.h264_in_fu = True
                return [start_code + nal_header + payload[2:]]
            if not self.h264_in_fu:
                return []
            if is_end:
                self.h264_in_fu = False
            return [payload[2:]]

        return []

    def _looks_like_h264(self, packet: RtpPacket) -> bool:
        if self._codec():
            return False
        if not packet.payload:
            return False
        nal_type = packet.payload[0] & 0x1F
        return nal_type in set(range(1, 24)) | {24, 28}

    def _reset_jpeg(self, timestamp: int) -> None:
        self.jpeg_timestamp = timestamp
        self.jpeg_chunks = {}
        self.jpeg_direct_parts = []
        self.jpeg_expected_offset = 0
        self.jpeg_valid = True
        self.jpeg_last_sequence = None
        self.jpeg_info = None

    def _drop_jpeg(self, reason: str, next_timestamp: int | None = None) -> None:
        self.jpeg_drop_count += 1
        self.jpeg_drop_reasons[reason] = self.jpeg_drop_reasons.get(reason, 0) + 1
        self.jpeg_last_drop_reason = reason
        reason_count = self.jpeg_drop_reasons[reason]
        if self.debug or reason_count in {1, 2, 3} or reason_count % 100 == 0:
            self._debug(
                "drop "
                f"reason={reason} reason_count={reason_count} total={self.jpeg_drop_count} "
                f"ts={self.jpeg_timestamp} last_seq={self.jpeg_last_sequence} "
                f"expected_offset={self.jpeg_expected_offset} chunks={len(self.jpeg_chunks)}",
                force=not self.debug,
            )
        if next_timestamp is not None:
            self._reset_jpeg(next_timestamp)

    def _drop_summary(self) -> str:
        if not self.jpeg_drop_reasons:
            return ""
        top = sorted(self.jpeg_drop_reasons.items(), key=lambda item: item[1], reverse=True)[:4]
        return ",".join(f"{reason}:{count}" for reason, count in top)

    def _debug(self, message: str, force: bool = False) -> None:
        if not self.debug and not force:
            return
        if not force and self.debug_limit >= 0 and self.debug_print_count >= self.debug_limit:
            return
        self.debug_print_count += 1
        prefix = "[VIDEO DEBUG]" if self.debug else "[VIDEO DROP]"
        print(prefix, message)

    def _jpeg_from_packet(self, packet: RtpPacket) -> bytes | None:
        payload = packet.payload
        if not payload:
            return None

        if self.jpeg_timestamp != packet.timestamp:
            if self.jpeg_timestamp is not None and (self.jpeg_chunks or self.jpeg_direct_parts):
                self._drop_jpeg("timestamp_changed_before_marker")
            self._reset_jpeg(packet.timestamp)

        if self.jpeg_last_sequence is not None and (
            (self.jpeg_last_sequence + 1) & 0xFFFF
        ) != packet.sequence:
            self.jpeg_valid = False
            self.jpeg_last_drop_reason = "sequence_gap"
        self.jpeg_last_sequence = packet.sequence

        if payload.startswith(b"\xff\xd8") or self.jpeg_direct_parts:
            self.jpeg_direct_parts.append(payload)
            if not packet.marker:
                self._debug(
                    f"direct part seq={packet.sequence} ts={packet.timestamp} "
                    f"payload={len(payload)} parts={len(self.jpeg_direct_parts)} marker=0"
                )
                return None
            data = b"".join(self.jpeg_direct_parts)
            valid = self.jpeg_valid and data.startswith(b"\xff\xd8")
            has_eoi = self._jpeg_has_eoi(data)
            self._debug(
                f"direct frame seq={packet.sequence} ts={packet.timestamp} "
                f"bytes={len(data)} parts={len(self.jpeg_direct_parts)} "
                f"valid_seq={valid} eoi={has_eoi}"
            )
            self._reset_jpeg((packet.timestamp + 1) & 0xFFFFFFFF)
            if not valid:
                self._drop_jpeg("direct_jpeg_sequence_gap")
                return None
            if not has_eoi:
                self._drop_jpeg("direct_jpeg_missing_eoi")
                return None
            self.jpeg_frame_count += 1
            return data

        info = self._parse_rtp_jpeg_payload(payload)
        if info is None:
            self._debug(
                f"bad rtp-jpeg header seq={packet.sequence} ts={packet.timestamp} "
                f"payload={len(payload)} marker={int(packet.marker)}"
            )
            if packet.marker:
                self._drop_jpeg("bad_rtp_jpeg_header", (packet.timestamp + 1) & 0xFFFFFFFF)
            return None

        offset = int(info["offset"])
        scan = info["scan"]
        if not isinstance(scan, bytes):
            self._debug(
                f"bad scan payload seq={packet.sequence} ts={packet.timestamp} "
                f"offset={offset} marker={int(packet.marker)}"
            )
            if packet.marker:
                self._drop_jpeg("bad_scan_payload", (packet.timestamp + 1) & 0xFFFFFFFF)
            return None
        expected_before = self.jpeg_expected_offset
        if offset == 0:
            self.jpeg_info = info
        if offset != self.jpeg_expected_offset:
            self.jpeg_valid = False
            self.jpeg_last_drop_reason = "fragment_offset_gap"
        if offset == 0 or packet.marker or not self.jpeg_valid:
            self._debug(
                f"rtp-jpeg seq={packet.sequence} ts={packet.timestamp} "
                f"marker={int(packet.marker)} payload={len(payload)} offset={offset} "
                f"expected={expected_before} scan={len(scan)} type={info['type']} "
                f"q={info['q']} size={info['width']}x{info['height']} "
                f"ri={info['restart_interval']} qtables={len(info['qtables']) if isinstance(info['qtables'], bytes) else 0} "
                f"valid={self.jpeg_valid}"
            )
        self.jpeg_chunks[offset] = scan
        self.jpeg_expected_offset = offset + len(scan)

        if not packet.marker:
            return None

        frame_info = self.jpeg_info or info
        chunks = self.jpeg_chunks
        valid = self.jpeg_valid
        self._reset_jpeg((packet.timestamp + 1) & 0xFFFFFFFF)
        if not valid:
            self._drop_jpeg(self.jpeg_last_drop_reason or "incomplete_frame")
            return None

        expected = 0
        parts: list[bytes] = []
        for chunk_offset in sorted(chunks):
            if chunk_offset != expected:
                self._drop_jpeg("missing_fragment")
                return None
            chunk = chunks[chunk_offset]
            parts.append(chunk)
            expected += len(chunk)

        scan_data = b"".join(parts)
        if scan_data.startswith(b"\xff\xd8"):
            if not self._jpeg_has_eoi(scan_data):
                self._drop_jpeg("embedded_jpeg_missing_eoi")
                return None
            jpeg = scan_data
            restart_interval = int(frame_info.get("restart_interval") or 0)
        else:
            restart_interval = self._restart_interval_for_scan(frame_info, scan_data)
            jpeg = self._jpeg_header(frame_info, restart_interval) + scan_data
        if not jpeg.endswith(b"\xff\xd9"):
            jpeg += b"\xff\xd9"
        self.jpeg_frame_count += 1
        self._debug(
            f"assembled frame={self.jpeg_frame_count} ts={packet.timestamp} "
            f"chunks={len(chunks)} scan={len(scan_data)} jpeg={len(jpeg)} "
            f"type={frame_info['type']} q={frame_info['q']} "
            f"size={frame_info['width']}x{frame_info['height']} "
            f"ri_raw={frame_info['restart_interval']} ri_used={restart_interval} "
            f"rst={self._restart_marker_count(scan_data)}"
        )
        return jpeg

    @staticmethod
    def _jpeg_has_eoi(data: bytes) -> bool:
        return data.rstrip(b"\x00").endswith(b"\xff\xd9")

    @staticmethod
    def _restart_marker_count(data: bytes) -> int:
        return sum(
            1
            for index in range(len(data) - 1)
            if data[index] == 0xFF and 0xD0 <= data[index + 1] <= 0xD7
        )

    def _restart_interval_for_scan(
        self,
        info: dict[str, int | bytes | None],
        scan_data: bytes,
    ) -> int:
        raw_interval = int(info.get("restart_interval") or 0)
        marker_count = self._restart_marker_count(scan_data)
        if marker_count <= 0:
            return raw_interval

        width = int(info["width"] or 640)
        height = int(info["height"] or 480)
        jpeg_type = int(info["type"] or 0) & 0x3F
        if jpeg_type == 0:
            mcu_width, mcu_height = 16, 8
        else:
            mcu_width, mcu_height = 16, 16

        mcu_cols = max(1, (width + mcu_width - 1) // mcu_width)
        mcu_rows = max(1, (height + mcu_height - 1) // mcu_height)
        total_mcus = mcu_cols * mcu_rows
        intervals = marker_count + 1

        if intervals == mcu_rows:
            calculated = mcu_cols
        elif total_mcus % intervals == 0:
            calculated = total_mcus // intervals
        else:
            calculated = max(1, round(total_mcus / intervals))

        if calculated != raw_interval:
            self._debug(
                f"dri calculated={calculated} raw={raw_interval} "
                f"markers={marker_count} mcu={mcu_cols}x{mcu_rows}"
            )
        return calculated

    @staticmethod
    def _looks_like_decoder_fill(frame, np) -> bool:
        if frame is None or frame.size == 0:
            return True
        if len(frame.shape) != 3 or frame.shape[2] < 3:
            return False

        # libjpeg paints missing scan data as large flat gray blocks. Drop those
        # frames like the APK's RTP/JPEG "DROP" parser does instead of showing them.
        grayish = np.all((frame >= 118) & (frame <= 138), axis=2)
        return float(grayish.mean()) > 0.22

    def _parse_rtp_jpeg_payload(self, payload: bytes) -> dict[str, int | bytes | None] | None:
        if len(payload) < 8:
            return None
        offset = (payload[1] << 16) | (payload[2] << 8) | payload[3]
        jpeg_type = payload[4]
        q = payload[5]
        width = max(1, payload[6]) * 8
        height = max(1, payload[7]) * 8
        pos = 8
        restart_interval = 0
        qtables: bytes | None = None

        if 64 <= jpeg_type <= 127:
            if len(payload) < pos + 4:
                return None
            restart_interval = int.from_bytes(payload[pos : pos + 2], "big")
            pos += 4

        if q >= 128 and offset == 0:
            if len(payload) < pos + 4:
                return None
            qtable_len = int.from_bytes(payload[pos + 2 : pos + 4], "big")
            if len(payload) < pos + 4 + qtable_len:
                return None
            qtables = payload[pos + 4 : pos + 4 + qtable_len]
            pos += 4 + qtable_len

        return {
            "offset": offset,
            "type": jpeg_type,
            "q": q,
            "width": width,
            "height": height,
            "restart_interval": restart_interval,
            "qtables": qtables,
            "scan": payload[pos:],
        }

    def _jpeg_header(
        self,
        info: dict[str, int | bytes | None],
        restart_interval: int | None = None,
    ) -> bytes:
        width = int(info["width"] or 640)
        height = int(info["height"] or 480)
        q = int(info["q"] or 75)
        qtables = info.get("qtables")
        if isinstance(qtables, bytes) and len(qtables) >= 128:
            luma = qtables[:64]
            chroma = qtables[64:128]
        else:
            quality = q if 1 <= q <= 99 else 75
            luma = self._scaled_quant_table(JPEG_LUMA_QUANT, quality)
            chroma = self._scaled_quant_table(JPEG_CHROMA_QUANT, quality)

        jpeg_type = int(info["type"] or 0)
        base_type = jpeg_type & 0x3F
        y_sampling = 0x22 if base_type == 1 else 0x21
        if restart_interval is None:
            restart_interval = int(info.get("restart_interval") or 0)
        header = bytearray(b"\xff\xd8")
        header.extend(bytes.fromhex("ffe000104a46494600010100000100010000"))
        if restart_interval:
            header.extend(b"\xff\xdd")
            header.extend((4).to_bytes(2, "big"))
            header.extend(restart_interval.to_bytes(2, "big"))
        header.extend(self._dqt_segment(0, luma))
        header.extend(self._dqt_segment(1, chroma))
        header.extend(b"\xff\xc0")
        header.extend((17).to_bytes(2, "big"))
        header.append(8)
        header.extend(height.to_bytes(2, "big"))
        header.extend(width.to_bytes(2, "big"))
        header.extend(bytes([3, 1, y_sampling, 0, 2, 0x11, 1, 3, 0x11, 1]))
        header.extend(JPEG_DHT)
        header.extend(bytes.fromhex("ffda000c03010002110311003f00"))
        return bytes(header)

    @staticmethod
    def _scaled_quant_table(table: tuple[int, ...], quality: int) -> bytes:
        scale = 5000 // quality if quality < 50 else 200 - (quality * 2)
        values = []
        for zigzag_index in JPEG_ZIGZAG:
            value = (table[zigzag_index] * scale + 50) // 100
            values.append(max(1, min(255, value)))
        return bytes(values)

    @staticmethod
    def _dqt_segment(table_id: int, table: bytes) -> bytes:
        return b"\xff\xdb" + (67).to_bytes(2, "big") + bytes([table_id]) + table[:64]


class DroneController:
    def __init__(
        self,
        session: RtspUdpSession,
        speed: int,
        axis_delta: int,
        altitude_hold: bool,
        hover_throttle: int,
        trim_ail: int,
        trim_ele: int,
        trim_rudd: int,
    ) -> None:
        self.session = session
        self.speed = normalize_speed_byte(speed)
        self.axis_delta = axis_delta
        self.altitude_hold = altitude_hold
        self.hover_throttle = clamp_byte(hover_throttle)
        self.trim_ail = clamp_byte(trim_ail)
        self.trim_ele = clamp_byte(trim_ele)
        self.trim_rudd = clamp_byte(trim_rudd)
        self.light = False
        self.headless = False
        self.hover_raise_count = 0
        self.hover_lower_count = 0
        self.trim_ail_raise_count = 0
        self.trim_ail_lower_count = 0
        self.trim_ele_raise_count = 0
        self.trim_ele_lower_count = 0
        self.pulse_until = 0.0
        self.pulse_state: HtjrPacketState | None = None

    def apply_common(self, state: HtjrPacketState) -> HtjrPacketState:
        state.speed = self.speed
        state.altitude_hold = self.altitude_hold
        state.light = self.light
        state.headless = self.headless
        state.trim_ail = self.trim_ail
        state.trim_ele = self.trim_ele
        state.trim_rudd = self.trim_rudd
        return state

    def neutral(self) -> HtjrPacketState:
        thr = self.hover_throttle if self.altitude_hold else 0
        return self.apply_common(HtjrPacketState(thr=thr))

    def adjust_hover_throttle(self, delta: int) -> None:
        if delta > 0:
            self.hover_raise_count += 1
        elif delta < 0:
            self.hover_lower_count += 1
        self.hover_throttle = clamp_byte(self.hover_throttle + delta)
        print("[DRONE] hover throttle:", self.hover_throttle)

    def adjust_trim_ail(self, delta: int) -> None:
        if delta > 0:
            self.trim_ail_raise_count += 1
        elif delta < 0:
            self.trim_ail_lower_count += 1
        self.trim_ail = clamp_byte(self.trim_ail + delta)
        print("[DRONE] trim AIL:", self.trim_ail)

    def adjust_trim_ele(self, delta: int) -> None:
        if delta > 0:
            self.trim_ele_raise_count += 1
        elif delta < 0:
            self.trim_ele_lower_count += 1
        self.trim_ele = clamp_byte(self.trim_ele + delta)
        print("[DRONE] trim ELE:", self.trim_ele)

    def print_hover_adjust_summary(self) -> None:
        print(
            "[DRONE] hover throttle adjustments: "
            f"raised={self.hover_raise_count} lowered={self.hover_lower_count} "
            f"final={self.hover_throttle}"
        )
        print(
            "[DRONE] trim adjustments: "
            f"AIL += {self.trim_ail_raise_count}, AIL -= {self.trim_ail_lower_count}, "
            f"ELE += {self.trim_ele_raise_count}, ELE -= {self.trim_ele_lower_count}"
        )
        print(
            "[DRONE] next-run tuning args: "
            f"--hover-throttle {self.hover_throttle} "
            f"--trim-ail {self.trim_ail} --trim-ele {self.trim_ele} --trim-rudd {self.trim_rudd}"
        )

    def pulse(self, state: HtjrPacketState, seconds: float) -> None:
        if self.altitude_hold and state.thr == 128:
            state.thr = 128
        self.pulse_state = self.apply_common(state)
        self.pulse_until = time.time() + seconds

    def current_pulse(self) -> HtjrPacketState | None:
        if self.pulse_state is not None and time.time() < self.pulse_until:
            return self.pulse_state
        self.pulse_state = None
        return None

    def send_state(self, state: HtjrPacketState) -> None:
        self.session.send_control(build_htjr_packet(self.apply_common(state)))


def run_pygame(
    controller: DroneController,
    interval: float,
    viewer: RtpVideoViewer | None = None,
) -> None:
    try:
        import pygame
    except ImportError:
        print("[WARN] pygame is not installed; falling back to terminal controls")
        run_terminal(controller, interval, viewer)
        return

    try:
        pygame.init()
        pygame.display.set_caption("HTJR Fixed Drone Controller")
        screen = pygame.display.set_mode((720, 330))
        font = pygame.font.SysFont(None, 25)
    except Exception as exc:
        print("[WARN] pygame display failed; falling back to terminal controls:", exc)
        run_terminal(controller, interval, viewer)
        return
    clock = pygame.time.Clock()

    running = True
    last_send = 0.0
    print_controls(gui=True)

    try:
        while running:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
                elif event.type == pygame.KEYDOWN:
                    if event.key in (pygame.K_ESCAPE, pygame.K_x):
                        running = False
                    elif event.key == pygame.K_q:
                        print("[DRONE] emergency down")
                        controller.pulse(HtjrPacketState(emergency_down=True), 1.0)
                    elif event.key == pygame.K_SPACE:
                        if viewer is None:
                            print("[PHOTO] video is off; no frame to capture")
                        else:
                            viewer.capture_picture()
                    elif event.key == pygame.K_t:
                        print("[DRONE] tiny up pulse")
                        controller.pulse(HtjrPacketState(flyup=True), 0.06)
                    elif event.key == pygame.K_g:
                        print("[DRONE] down/land pulse")
                        controller.pulse(HtjrPacketState(flydown=True), 0.20)
                    elif event.key == pygame.K_e:
                        print("[DRONE] gyro calibrate")
                        controller.pulse(HtjrPacketState(gyro_calibrate=True), 1.0)
                    elif event.key == pygame.K_h:
                        controller.headless = not controller.headless
                        print("[DRONE] headless:", controller.headless)
                    elif event.key == pygame.K_o:
                        controller.altitude_hold = not controller.altitude_hold
                        print("[DRONE] altitude hold:", controller.altitude_hold)
                    elif event.key == pygame.K_l:
                        controller.light = not controller.light
                        print("[DRONE] light:", controller.light)
                    elif event.key == pygame.K_u:
                        controller.adjust_hover_throttle(2)
                    elif event.key == pygame.K_j:
                        controller.adjust_hover_throttle(-2)
                    elif event.key in (pygame.K_6, pygame.K_KP6):
                        controller.adjust_trim_ail(2)
                    elif event.key in (pygame.K_4, pygame.K_KP4):
                        controller.adjust_trim_ail(-2)
                    elif event.key in (pygame.K_8, pygame.K_KP8):
                        controller.adjust_trim_ele(2)
                    elif event.key in (pygame.K_2, pygame.K_KP2):
                        controller.adjust_trim_ele(-2)

            now = time.time()
            if now - last_send >= interval:
                state = controller.current_pulse() or pygame_state(controller)
                controller.send_state(state)
                last_send = now

            draw_status(screen, font, controller)
            pygame.display.flip()
            clock.tick(60)
    finally:
        pygame.quit()


def pygame_state(controller: DroneController) -> HtjrPacketState:
    try:
        import pygame
    except ImportError:  # pragma: no cover
        return controller.neutral()

    keys = pygame.key.get_pressed()
    delta = controller.axis_delta
    state = controller.neutral()

    if keys[pygame.K_w]:
        state.ele = 128 + delta
    elif keys[pygame.K_s]:
        state.ele = 128 - delta

    if keys[pygame.K_a]:
        state.ail = 128 - delta
    elif keys[pygame.K_d]:
        state.ail = 128 + delta

    if keys[pygame.K_LEFT]:
        state.rudd = 128 - delta
    elif keys[pygame.K_RIGHT]:
        state.rudd = 128 + delta

    if keys[pygame.K_UP]:
        if controller.altitude_hold:
            state.flyup = True
        else:
            state.thr = min(255, 128 + controller.axis_delta)
    elif keys[pygame.K_DOWN]:
        if controller.altitude_hold:
            state.flydown = True
        else:
            state.thr = max(0, 128 - controller.axis_delta)

    return state


def draw_status(screen, font, controller: DroneController) -> None:
    try:
        import pygame
    except ImportError:  # pragma: no cover
        return

    screen.fill((18, 18, 20))
    lines = [
        "HTJR fixed controller",
        f"Speed byte: {controller.speed}    Axis delta: {controller.axis_delta}    Hover THR: {controller.hover_throttle}",
        f"Trim AIL/ELE/RUDD: {controller.trim_ail}/{controller.trim_ele}/{controller.trim_rudd}",
        f"Altitude hold: {controller.altitude_hold}    Headless: {controller.headless}    Light: {controller.light}",
        "Space photo | T up pulse | G down pulse | Q emergency | E gyro",
        "Hold Up/Down fly up/down | W/S pitch | A/D roll | Left/Right yaw",
        "U/J hover | trim 4/6 AIL, 2/8 ELE | O altitude | X/Esc quit",
    ]
    y = 24
    for line in lines:
        rendered = font.render(line, True, (230, 230, 230))
        screen.blit(rendered, (22, y))
        y += 42


def run_terminal(
    controller: DroneController,
    interval: float,
    viewer: RtpVideoViewer | None = None,
) -> None:
    print_controls(gui=False)
    old_settings = termios.tcgetattr(sys.stdin)
    tty.setcbreak(sys.stdin.fileno())
    active_state: HtjrPacketState | None = None
    active_until = 0.0
    last_send = 0.0

    try:
        while True:
            ready, _, _ = select.select([sys.stdin], [], [], 0)
            if ready:
                key = sys.stdin.read(1)
                if key in ("x", "X", "\x1b"):
                    break
                if key in ("q", "Q"):
                    print("[DRONE] emergency down")
                    active_state = HtjrPacketState(emergency_down=True)
                    active_until = time.time() + 1.0
                elif key == " ":
                    if viewer is None:
                        print("[PHOTO] video is off; no frame to capture")
                    else:
                        viewer.capture_picture()
                elif key == "t":
                    print("[DRONE] tiny up pulse")
                    active_state = HtjrPacketState(flyup=True)
                    active_until = time.time() + 0.06
                elif key == "g":
                    print("[DRONE] down/land pulse")
                    active_state = HtjrPacketState(flydown=True)
                    active_until = time.time() + 0.20
                elif key == "w":
                    active_state = HtjrPacketState(ele=128 + controller.axis_delta)
                    active_until = time.time() + 0.20
                elif key == "s":
                    active_state = HtjrPacketState(ele=128 - controller.axis_delta)
                    active_until = time.time() + 0.20
                elif key == "a":
                    active_state = HtjrPacketState(ail=128 - controller.axis_delta)
                    active_until = time.time() + 0.20
                elif key == "d":
                    active_state = HtjrPacketState(ail=128 + controller.axis_delta)
                    active_until = time.time() + 0.20
                elif key == "i":
                    active_state = HtjrPacketState(flyup=True)
                    active_until = time.time() + 0.06
                elif key == "k":
                    active_state = HtjrPacketState(flydown=True)
                    active_until = time.time() + 0.12
                elif key == "h":
                    active_state = HtjrPacketState(rudd=128 - controller.axis_delta)
                    active_until = time.time() + 0.20
                elif key == "l":
                    active_state = HtjrPacketState(rudd=128 + controller.axis_delta)
                    active_until = time.time() + 0.20
                elif key == "o":
                    controller.altitude_hold = not controller.altitude_hold
                    print("[DRONE] altitude hold:", controller.altitude_hold)
                elif key in ("u", "U"):
                    controller.adjust_hover_throttle(2)
                elif key in ("j", "J"):
                    controller.adjust_hover_throttle(-2)
                elif key == "6":
                    controller.adjust_trim_ail(2)
                elif key == "4":
                    controller.adjust_trim_ail(-2)
                elif key == "8":
                    controller.adjust_trim_ele(2)
                elif key == "2":
                    controller.adjust_trim_ele(-2)

            now = time.time()
            if now - last_send >= interval:
                if active_state is not None and now < active_until:
                    state = controller.apply_common(active_state)
                else:
                    active_state = None
                    state = controller.neutral()
                controller.send_state(state)
                last_send = now
            time.sleep(0.005)
    finally:
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)


def print_controls(gui: bool) -> None:
    print()
    print("Controls:")
    if gui:
        print("  Space photo | T tiny up pulse | G down pulse | Q emergency down | E gyro calibrate")
        print("  Hold Up/Down fly up/down | W/S pitch | A/D roll | Left/Right yaw")
        print("  U/J hover throttle | 4/6 AIL trim | 2/8 ELE trim | O altitude hold | X/Esc quit")
    else:
        print("  Space photo | t tiny up | g down | q emergency")
        print("  w/s pitch | a/d roll | i/k up/down | h/l yaw | x quit")
        print("  u/j hover throttle | 4/6 AIL trim | 2/8 ELE trim | o toggles altitude hold")
    print()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default=DEFAULT_DRONE_IP)
    parser.add_argument("--port", type=int, default=DEFAULT_RTSP_PORT)
    parser.add_argument("--url", default=DEFAULT_RTSP_URL)
    parser.add_argument("--client-port", type=int, default=None)
    parser.add_argument(
        "--speed",
        type=int,
        default=30,
        help="APK speed byte. The real app sends only 30, 60, or 100.",
    )
    parser.add_argument(
        "--axis-delta",
        type=int,
        default=90,
        help="Raw joystick delta before APK speed scaling.",
    )
    parser.add_argument("--trim-ail", type=int, default=128)
    parser.add_argument("--trim-ele", type=int, default=128)
    parser.add_argument("--trim-rudd", type=int, default=128)
    parser.add_argument(
        "--hover-throttle",
        type=int,
        default=128,
        help="Neutral THR byte while altitude hold is enabled. Lower this if the drone slowly climbs.",
    )
    parser.add_argument("--send-interval", type=float, default=0.04)
    parser.add_argument(
        "--no-altitude-hold",
        action="store_true",
        help="Use non-altitude-hold throttle style: neutral THR=0 instead of 128.",
    )
    parser.add_argument("--no-video", action="store_true")
    parser.add_argument("--terminal", action="store_true")
    parser.add_argument("--verbose-rtsp", action="store_true")
    parser.add_argument(
        "--capture-dir",
        default="captures",
        help="Folder for Space-key camera pictures.",
    )
    parser.add_argument(
        "--video-debug",
        action="store_true",
        help="Print detailed RTP/JPEG packet assembly diagnostics.",
    )
    parser.add_argument(
        "--video-debug-limit",
        type=int,
        default=120,
        help="Maximum detailed RTP/JPEG debug lines. Use -1 for unlimited.",
    )
    parser.add_argument(
        "--video-dump-dir",
        default=None,
        help="Optional folder for reconstructed JPEG frames before OpenCV decodes them.",
    )
    parser.add_argument(
        "--video-dump-limit",
        type=int,
        default=8,
        help="Maximum reconstructed JPEG files to write when --video-dump-dir is set.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    print("Connect this computer to the drone Wi-Fi first.")
    print("[INFO] RTSP URL:", args.url)
    altitude_hold = not args.no_altitude_hold
    speed = normalize_speed_byte(args.speed)
    print("[INFO] Packet speed:", speed)
    print("[INFO] Axis delta:", args.axis_delta)
    print("[INFO] Hover throttle:", clamp_byte(args.hover_throttle))
    print("[INFO] Trim AIL/ELE/RUDD:", args.trim_ail, args.trim_ele, args.trim_rudd)
    print("[INFO] Altitude hold:", altitude_hold)
    print("[INFO] Video:", "off" if args.no_video else "on")
    if not args.no_video:
        print("[INFO] Capture dir:", args.capture_dir)
    if args.video_debug:
        print("[INFO] Video debug: on")
    if args.video_dump_dir:
        print("[INFO] Video dump dir:", args.video_dump_dir)

    session = RtspUdpSession(
        host=args.host,
        port=args.port,
        url=args.url,
        client_port_base=args.client_port,
        verbose=args.verbose_rtsp,
    )
    viewer: RtpVideoViewer | None = None
    if not args.no_video:
        viewer = RtpVideoViewer(
            session,
            debug=args.video_debug,
            debug_limit=args.video_debug_limit,
            dump_dir=args.video_dump_dir,
            dump_limit=args.video_dump_limit,
            capture_dir=args.capture_dir,
        )
        session.add_rtp_callback(viewer.on_rtp_packet)

    controller = DroneController(
        session,
        speed=speed,
        axis_delta=args.axis_delta,
        altitude_hold=altitude_hold,
        hover_throttle=args.hover_throttle,
        trim_ail=args.trim_ail,
        trim_ele=args.trim_ele,
        trim_rudd=args.trim_rudd,
    )

    try:
        session.connect()
        if viewer is not None:
            viewer.start()

        # Send neutral a few times so the command path is warm before key input.
        neutral = build_htjr_packet(controller.neutral())
        for _ in range(5):
            session.send_control(neutral)
            time.sleep(args.send_interval)

        if args.terminal:
            run_terminal(controller, args.send_interval, viewer)
        else:
            run_pygame(controller, args.send_interval, viewer)
    finally:
        print("[INFO] closing")
        controller.print_hover_adjust_summary()
        try:
            neutral = build_htjr_packet(controller.neutral())
            for _ in range(5):
                session.send_control(neutral)
                time.sleep(args.send_interval)
        except Exception:
            pass
        if viewer is not None:
            viewer.stop()
        session.close()


if __name__ == "__main__":
    main()
