"""add_snapshots_and_product_value

Revision ID: 79b4056d6ad4
Revises: 68d4921ab629
Create Date: 2026-03-25 07:00:52.264769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b4056d6ad4'
down_revision: Union[str, None] = '68d4921ab629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshots_id'), 'inventory_snapshots', ['id'], unique=False)
    op.create_table('inventory_snapshot_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['inventory_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshot_items_id'), 'inventory_snapshot_items', ['id'], unique=False)
    op.add_column('products', sa.Column('value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'value')
    op.drop_index(op.f('ix_inventory_snapshot_items_id'), table_name='inventory_snapshot_items')
    op.drop_table('inventory_snapshot_items')
    op.drop_index(op.f('ix_inventory_snapshots_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    # ### end Alembic commands ###
